version: '3.8'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=b14ck-cyph3R
      - DB_NAME=chessinchunks
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=mysql://root:b14ck-cyph3R@mysql:3306/chessinchunks
      - INVITATION_SECRET=NZAXrxqvMDVUgd3jRPG9tn
      - JWT_SECRET=NPFC6yXK7jD9Hw4xVUZBkR
      - RESET_PASSWORD_SECRET=KhW49gT2XFtnUSdGCPauyv
      - FRONTEND_URL=http://localhost:3001
      - CHESSINCHUNKS_URL=http://localhost:3000
      - EMAIL_USER=paritbhardwaj019@gmail.com
      - EMAIL_PASSWORD=jdcf fvcb wafx gniw
      - STRIPE_SECRET_KEY=sk_test_51QTP2fKwH6vRuntqfSUjwolNT0Y7Gay9nQh3xxCajXi9L8TlBXgl9hNkj6g5rAE7HBN5F2POHpS5sZnRlPS74Sng00qkGN97cW
      - STRIPE_PUBLISHABLE_KEY=pk_test_51QTP2fKwH6vRuntqKTZohnkSxcsfvJUyffS36Gv5bqV7vH2vyleRkfFukKg1upErT6mjBCh2UrUtIDtVmDk2cKW700HTuhi5g3
      - STRIPE_WEBHOOK_SECRET=whsec_wtd4irorY3RM7DTg0I4GWnFakizCYgnE
      - CLOUDINARY_CLOUD_NAME=dooyfismf
      - CLOUDINARY_API_KEY=619732951573262
      - CLOUDINARY_API_SECRET=AuY4So-0HalqwR3eTcW8XxHmBf4'
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=b14ck-cyph3R
      - MYSQL_DATABASE=chessinchunks
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-pb14ck-cyph3R',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
