const express = require('express');
const academyRouter = require('../../modules/academy/routes/academy.route');
const messageRouter = require('../../modules/message/routes/message.route');
const chatRouter = require('../../modules/chat/routes/chat.route');
const friendRequestRouter = require('../../modules/friendRequest/routes/friendRequest.route');
const channelRouter = require('../../modules/channel/routes/channel.route');
const taskRouter = require('../../modules/task/routes/task.route');
const permissionRouter = require('../../modules/permission/routes/permission.route');
const eventRouter = require('../../modules/event/routes/event.route');
const notificationRouter = require('../../modules/notification/routes/notification.route');
const systemCodeRouter = require('../../modules/systemCode/routes/systemCode.route');
const stripeWebhookRouter = require('./webhook/stripe');
const academyProgramRouter = require('../../modules/academyProgram/routes/academyProgram.route');
const adminRouter = require('../../modules/admin/routes/admin.route');
const authRouter = require('../../modules/auth/routes/auth.route');
const batchRouter = require('../../modules/batch/routes/batch.route');
const pageRouter = require('../../modules/page/routes/page.route');
const batchReportRouter = require('../../modules/batchSnapshot/routes/batchReport.route');
const coachRouter = require('../../modules/coach/routes/coach.route');
const dashboardRouter = require('../../modules/dashboard/routes/dashboard.route');
const enrollmentReportRouter = require('../../modules/enrollmentReport/routes/enrollmentReport.route');
const goalRouter = require('../../modules/goal/routes/goal.route');
const invitationRouter = require('../../modules/invitation/routes/invitation.route');
const navigationRouter = require('../../modules/navigation/routes/navigation.route');
const portalSubscriberRouter = require('../../modules/portalSubscriber/routes/portalSubscriber.route');
const quizRouter = require('../../modules/quiz/routes/quiz.route');
const studentRouter = require('../../modules/student/routes/student.route');
const studentProfileRouter = require('../../modules/studentProfile/routes/studentProfile.route');
const studentReportRouter = require('../../modules/studentReport/routes/studentReport.route');
const studentSignupRouter = require('../../modules/studentSignup/routes/studentSignup.route');
const superAdminRouter = require('../../modules/superAdmin/routes/superAdmin.route');
const userRouter = require('../../modules/user/routes/user.route');
const coachSignupRouter = require('../../modules/coach-signups/routes/coachSignup.route');

const router = express.Router();

router.use('/academy', academyRouter);
router.use('/superadmin', superAdminRouter);
router.use('/coach', coachRouter);
router.use('/batch', batchRouter);
router.use('/auth', authRouter);
router.use('/student', studentRouter);
router.use('/invitation', invitationRouter);
router.use('/user', userRouter);
router.use('/dashboard', dashboardRouter);
router.use('/goal', goalRouter);
router.use('/messages', messageRouter);
router.use('/chats', chatRouter);
router.use('/friend-requests', friendRequestRouter);
router.use('/channels', channelRouter);
router.use('/tasks', taskRouter);
router.use('/permission', permissionRouter);
router.use('/events', eventRouter);
router.use('/notifications', notificationRouter);
router.use('/system-code', systemCodeRouter);
router.use('/webhook', stripeWebhookRouter);
router.use('/academy-programs', academyProgramRouter);
router.use('/student-signups', studentSignupRouter);
router.use('/quiz', quizRouter);
router.use('/navigation', navigationRouter);
router.use('/pages', pageRouter);
router.use('/reports/batches', batchReportRouter);
router.use('/reports/enrollments', enrollmentReportRouter);
router.use('/reports/students', studentReportRouter);
router.use('/admins', adminRouter);
router.use('/portal-subscribers', portalSubscriberRouter);
router.use('/student-profile', studentProfileRouter);
router.use('/coach-signup', coachSignupRouter);

module.exports = router;
