const express = require('express');

const academyRouter = require('./academy.route');
const superAdminRouter = require('./superAdmin.route');
const coachRouter = require('./coach.route');
const adminRouter = require('./admin.route');
const batchRouter = require('./batch.route');
const authRouter = require('./auth.route');
const studentRouter = require('./student.route');
const invitationRouter = require('./invitation.route');
const userRouter = require('./user.route');
const dashboardRouter = require('./dashboard.route');
const goalRouter = require('./goal.route');
const messageRouter = require('./messageRouter');
const chatRouter = require('./chatRouter');
const friendRequestRouter = require('./friendRequestRouter');
const channelRouter = require('./channelRouter');
const taskRouter = require('./task.route');
const permissionRouter = require('./permission.route');
const eventRouter = require('./event.route');
const notificationRouter = require('./notification.route');
const systemCodeRouter = require('./systemCode.route');
const stipeWebhookRouter = require('./webhook/stipe');
const academyProgramRouter = require('./academyProgram.route');
const studentSignupRouter = require('./studentSignup.route');
const quizRouter = require('./quiz.route');

const router = express.Router();

router.use('/academy', academyRouter);
router.use('/superadmin', superAdminRouter);
router.use('/admin', adminRouter);
router.use('/coach', coachRouter);
router.use('/batch', batchRouter);
router.use('/auth', authRouter);
router.use('/student', studentRouter);
router.use('/invitation', invitationRouter);
router.use('/user', userRouter);
router.use('/dashboard', dashboardRouter);
router.use('/goal', goalRouter);
router.use('/messages', messageRouter);
router.use('/chats', chatRouter);
router.use('/friend-requests', friendRequestRouter);
router.use('/channels', channelRouter);
router.use('/tasks', taskRouter);
router.use('/permission', permissionRouter);
router.use('/events', eventRouter);
router.use('/notifications', notificationRouter);
router.use('/system-code', systemCodeRouter);
router.use('/webhook', stipeWebhookRouter);
router.use('/academy-programs', academyProgramRouter);
router.use('/student-signups', studentSignupRouter);
router.use('/quiz', quizRouter);

module.exports = router;
