const ROLE_CONSTANT = {
  ROLE: {
    SUPER_ADMIN: 'SUPER_ADMIN',
    ADMIN: 'ADMIN',
    COACH: 'COACH',
    STUDENT: 'STUDENT',
    SUBSCRIBER: 'SUBSCRIBER',
  },
  ADMIN_ROLE: {
    MASTER_ADMIN: 'MASTER_ADMIN',
    ACADEMY_ADMIN: 'ACADEMY_ADMIN',
  },
  COACH_ROLE: {
    HEAD_COACH: 'HEAD_COACH',
    SENIOR_COACH: 'SENIOR_COACH',
    JUNIOR_COACH: 'JUNIOR_COACH',
    PUZZLE_MASTER: 'PUZZLE_MASTER',
    PUZZLE_MASTER_SCHOLAR: 'PUZZLE_MASTER_SCHOLAR',
  },
};

module.exports = ROLE_CONSTANT;
