const CONSTANTS = {
  ROLE: {
    SUPER_ADMIN: 'SUPER_ADMIN',
    ACADEMY_ADMIN: 'ACADEMY_ADMIN',
    COACH: {
      HEAD_COACH: 'HEAD_COACH',
      SENIOR_COACH: 'SENIOR_COACH',
      JUNIOR_COACH: 'JUNIOR_COACH',
      PUZZLE_MASTER: 'PUZZLE_MASTER',
      PUZZLE_MASTER_SCHOLAR: 'PUZZLE_MASTER_SCHOLAR',
    },
    STUDENT: 'STUDENT',
    SUBSCRIBER: 'SUBSCRIBER',
  },
};

module.exports = CONSTANTS;
